Models/ErrorViewModel.cs
namespace ExceptionHandling.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ExceptionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using NLog;
using NLog.Fluent;
using NLog.Web;
using System.Data.SqlClient;
using System.Diagnostics.Metrics;

namespace ExceptionHandling.Controllers
{
    public class ExceptionController : Controller
    {

        //declare Nlog logger object 
        private readonly Logger logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

        private readonly IConfiguration _configuration;

        public ExceptionController(IConfiguration configuration)
        {
            _configuration = configuration;
        }


        public IActionResult Index()
        {
            ViewData["counter"] = 0;
            return View(ViewData);
        }

        
        // method to increment the counter
        // generates custom exception if counter value greater than 10
        public IActionResult ExceptionCounter(int counter)
        {
            try
            {
                if (counter < 10)
                {
                    logger.Debug("Increasing counter value by 1");

                    ViewData["counter"] = ++counter;
                    return View("Index", ViewData);
                }
                else
                {
                    logger.Debug("Exceeded the count limit");  //logging in text file 

                    throw new InvalidDataException("You have exceeded the count limit");  //custom exception thrown
                    
                }
            }
            catch(Exception ex)
            {
                logger.Error(ex);   //logs error in log -file
                return View();
                throw;
            }
        }
    

        //method to connect to database
        [HttpGet]
        public IActionResult DatabaseConnect(bool flag)
        {
            //flag false initially to load get view
            if(!flag) 
            {
                ViewData["message"] = true;
                return View();
            }
            else
            {
                ViewData["message"] = false;
                

                //setting db connection
                SqlConnection cnn; 
                string connetionString = _configuration.GetConnectionString("DatabaseConnection");
                
                cnn = new SqlConnection(connetionString);

                try
                {
                    logger.Debug("Connection to database initiated");
                    
                    cnn.Open();
                    return View(); //return connected message
                }
                catch (Exception ex)
                {
                    logger.Error(ex);
                    return View("ExceptionCounter");  //return exception page
                    throw;
                }
                finally 
                {
                    //closing database connection
                    logger.Debug("Closing database connection");
                    cnn.Close();
                }

            }
            
        }
    }
}

Controllers/HomeController.cs
using ExceptionHandling.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExceptionHandling.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Exception/DatabaseConnect.cshtml
@{
    ViewData["Title"] = "Database Exception Page";

    var message = ViewData["message"];
}

<div class="text-center align-content-center">
    <div><h2>Connect to database</h2></div>
    <div>
        <button><a asp-action="DatabaseConnect" asp-route-flag=true>Connect</a></button>
    </div>

    <br/>
    <div><span hidden="@message">Database connected successfully!</span></div>
</div>

Views/Exception/ExceptionCounter.cshtml
@{
    ViewData["Title"] = "Exception Page";
}

<div class="text-center">
    <h2 class="display-4">Something went wrong!</h2>
</div>

Views/Exception/Index.cshtml
@{
    ViewData["Title"] = "Exception Page";

    var counter = ViewData["counter"];
}

<div class="text-center align-content-center">
    <div><h2>Increment the count by 1. You can only increment counter till 10</h2></div>
    <div>
        <button><a asp-action="ExceptionCounter" asp-route-counter="@counter">@counter</a></button>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExceptionHandling</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExceptionHandling.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExceptionHandling</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exception" asp-action="Index">Custom Exception</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exception" asp-action="DatabaseConnect">Database Exception</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExceptionHandling - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>